setGeneric("wtFiles", function(obj) standardGeneric("wtFiles"))
setGeneric("mutFiles", function(obj) standardGeneric("mutFiles"))
setGeneric("refFasta", function(obj) standardGeneric("refFasta"))
setGeneric("gtf", function(obj) standardGeneric("gtf"))
setGeneric("outputFolder", function(obj) standardGeneric("outputFolder"))
setGeneric("includeScaffolds", function(obj) standardGeneric("includeScaffolds"))
setGeneric("minDepth", function(obj) standardGeneric("minDepth"))
setGeneric("homozygoteCutoff", function(obj) standardGeneric("homozygoteCutoff"))
setGeneric("minBaseQuality", function(obj) standardGeneric("minBaseQuality"))
setGeneric("minMapQuality", function(obj) standardGeneric("minMapQuality"))
setGeneric("fileAggregation", function(obj) standardGeneric("fileAggregation"))
setGeneric("distancePower", function(obj) standardGeneric("distancePower"))
setGeneric("peakIntervalWidth", function(obj) standardGeneric("peakIntervalWidth"))
setGeneric("loessOptResolution", function(obj) standardGeneric("loessOptResolution"))
setGeneric("loessOptCutFactor", function(obj) standardGeneric("loessOptCutFactor"))

setGeneric("wtFiles<-", function(obj, value) standardGeneric("wtFiles<-"))
setGeneric("mutFiles<-", function(obj, value) standardGeneric("mutFiles<-"))
setGeneric("refFasta<-", function(obj, value) standardGeneric("refFasta<-"))
setGeneric("gtf<-", function(obj, value) standardGeneric("gtf<-"))
setGeneric("outputFolder<-", function(obj, value) standardGeneric("outputFolder<-"))
setGeneric("includeScaffolds<-", function(obj, value) standardGeneric("includeScaffolds<-"))
setGeneric("minDepth<-", function(obj, value) standardGeneric("minDepth<-"))
setGeneric("homozygoteCutoff<-", function(obj, value) standardGeneric("homozygoteCutoff<-"))
setGeneric("minBaseQuality<-", function(obj, value) standardGeneric("minBaseQuality<-"))
setGeneric("minMapQuality<-", function(obj, value) standardGeneric("minMapQuality<-"))
setGeneric("fileAggregation<-", function(obj, value) standardGeneric("fileAggregation<-"))
setGeneric("distancePower<-", function(obj, value) standardGeneric("distancePower<-"))
setGeneric("peakIntervalWidth<-", function(obj, value) standardGeneric("peakIntervalWidth<-"))
setGeneric("loessOptResolution<-", function(obj, value) standardGeneric("loessOptResolution<-"))
setGeneric("loessOptCutFactor<-", function(obj, value) standardGeneric("loessOptCutFactor<-"))

setGeneric("param", function(obj) standardGeneric("param"))
setGeneric("param<-", function(obj, value) standardGeneric("param<-"))
setGeneric("snpDistance", function(obj) standardGeneric("snpDistance"))
setGeneric("peaks", function(obj) standardGeneric("peaks"))
setGeneric("candidates", function(obj) standardGeneric("candidates"))
