setGeneric("refGenome", function(obj) standardGeneric("refGenome"))
setGeneric("wtFiles", function(obj) standardGeneric("wtFiles"))
setGeneric("mutFiles", function(obj) standardGeneric("mutFiles"))
setGeneric("vepFlags", function(obj) standardGeneric("vepFlags"))
setGeneric("species", function(obj) standardGeneric("species"))
setGeneric("homozygoteCutoff", function(obj) standardGeneric("homozygoteCutoff"))
setGeneric("distancePower", function(obj) standardGeneric("distancePower"))
setGeneric("peakIntervalWidth", function(obj) standardGeneric("peakIntervalWidth"))
setGeneric("minDepth", function(obj) standardGeneric("minDepth"))
setGeneric("minBaseQuality", function(obj) standardGeneric("minBaseQuality"))
setGeneric("minMapQuality", function(obj) standardGeneric("minMapQuality"))
setGeneric("loessOptResolution", function(obj) standardGeneric("loessOptResolution"))
setGeneric("loessOptCutFactor", function(obj) standardGeneric("loessOptCutFactor"))
setGeneric("naCutoff", function(obj) standardGeneric("naCutoff"))
setGeneric("outputFolder", function(obj) standardGeneric("outputFolder"))
setGeneric("fileAggregation", function(obj) standardGeneric("fileAggregation"))

setGeneric("refGenome<-",function(obj,value) standardGeneric("refGenome<-"))
setGeneric("wtFiles<-",function(obj,value) standardGeneric("wtFiles<-"))
setGeneric("mutFiles<-",function(obj,value) standardGeneric("mutFiles<-"))
setGeneric("vepFlags<-",function(obj,value) standardGeneric("vepFlags<-"))
setGeneric("species<-",function(obj,value) standardGeneric("species<-"))
setGeneric("homozygoteCutoff<-",function(obj,value) standardGeneric("homozygoteCutoff<-"))
setGeneric("distancePower<-",function(obj,value) standardGeneric("distancePower<-"))
setGeneric("peakIntervalWidth<-",function(obj,value) standardGeneric("peakIntervalWidth<-"))
setGeneric("minDepth<-",function(obj,value) standardGeneric("minDepth<-"))
setGeneric("minBaseQuality<-",function(obj,value) standardGeneric("minBaseQuality<-"))
setGeneric("minMapQuality<-",function(obj,value) standardGeneric("minMapQuality<-"))
setGeneric("loessOptResolution<-",function(obj,value) standardGeneric("loessOptResolution<-"))
setGeneric("loessOptCutFactor<-",function(obj,value) standardGeneric("loessOptCutFactor<-"))
setGeneric("naCutoff<-",function(obj,value) standardGeneric("naCutoff<-"))
setGeneric("outputFolder<-",function(obj,value) standardGeneric("outputFolder<-"))
setGeneric("fileAggregation<-",function(obj,value) standardGeneric("fileAggregation<-"))

setGeneric("param", function(obj) standardGeneric("param"))
setGeneric("distance", function(obj) standardGeneric("distance"))
setGeneric("peaks", function(obj) standardGeneric("peaks"))
setGeneric("candidates", function(obj) standardGeneric("candidates"))
